# Diffusive analysis

## Catfish Cloud Comparison
```{r, echo = F}
embed_url("https://youtu.be/y2M4VBIx9a0")
```

```{r catfish average diff co2}
catfish_pts_06 %>% mutate(date = "9/6-9/7") %>% bind_rows(catfish_pts_18 %>% mutate(date = "9/18-9/19")) %>% group_by(date, trip) %>% summarize(mean_co2 = mean(flux_co2_g_hr)) %>% ggplot(aes(trip, mean_co2, color = date))+geom_line()
```

## Deans Cloud Comparison
```{r, echo = F}
library("vembedr")
embed_url("https://youtu.be/oMqE6EcmbUg")
```

```{r deans average diff co2}
deans_pts_16 %>% mutate(date = "8/16-8/17") %>% bind_rows(deans_pts_30 %>% mutate(date = "8/30-8/31")) %>% group_by(date, trip) %>% summarize(mean_co2 = mean(flux_co2_g_hr)) %>% ggplot(aes(trip, mean_co2, color = date))+geom_line()
```

```{r catfish average diff ch4}
catfish_pts_06 %>% mutate(date = "9/6-9/7") %>% bind_rows(catfish_pts_18 %>% mutate(date = "9/18-9/19")) %>% group_by(date, trip) %>% summarize(mean_ch4 = mean(flux_ch4_g_hr)) %>% ggplot(aes(trip, mean_ch4, color = date))+geom_line()

catfish_pts_06 %>% mutate(date = "9/6-9/7") %>% bind_rows(catfish_pts_18 %>% mutate(date = "9/18-9/19")) %>% group_by(date, trip) %>% summarize(med_ch4 = median(flux_ch4_g_hr)) %>% ggplot(aes(trip, med_ch4, color = date))+geom_line()
```

```{r deans average diff ch4}
deans_pts_16 %>% mutate(date = "8/16-8/17") %>% bind_rows(deans_pts_30 %>% mutate(date = "8/30-8/31")) %>% group_by(date, trip) %>% summarize(mean_ch4 = mean(flux_ch4_g_hr)) %>% ggplot(aes(trip, mean_ch4, color = date))+geom_line()
```

