---
title: "Equilibration Calculations"
author: "L. Naslund"
date: "2022-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

temps <- read.csv("../1-Raw Data/dissolved-gas/EquilibrationTemps_2022.csv") %>% 
  mutate(Vial = as.character(Vial))

# air gas certifies that CO and CO2 impurities do not exceed 1% in ultra pure zero air, so as a conservative approach, I set CO2 purge gas concentration to 1 ppm
```

```{r}
data_20221011 <- read.csv("../1-Raw Data/dissolved-gas/GC_Data_20221011_equil.csv") %>% 
  left_join(temps %>% select(Vial, Temp), by = "Vial") %>% 
  mutate(Barometric_P = 0.93, # in atm
         Headspace_equil_P = 0.93, # in atm
         Headspace_vol = 0.02, # in L
         Liquid_vol = 0.04, # in L
         Final_Headspace_Mixing_CH4_ppm = CH4.conc.ppm, 
         Final_Headspace_Mixing_CO2_ppm = CO2.conc.ppm, 
         Source_Gas_Mixing_CH4_ppm = 0, 
         Source_Gas_Mixing_CO2_ppm = 1, 
         Headspace_Equil_Temp_K = Temp + 273.15, # in K
         Bunsen_Sol_CH4 = (2.7182818^(-67.1962+(99.1624*(100/Headspace_Equil_Temp_K))+(27.9015*log(Headspace_Equil_Temp_K/100)))), 
         Bunsen_Sol_CO2 = (2.7182818^(-58.0931+(90.5069*(100/Headspace_Equil_Temp_K))+(22.294*log(Headspace_Equil_Temp_K/100))))*((0.0821*273.15)+((-1636.75+(12.0408*273.15)-(3.27957*0.01*273.15*273.15)+(3.16528*0.00001*273.15*273.15*273.15))/1000)), # L/L-atm
         
         Source_Gas_CH4_umol = (Source_Gas_Mixing_CH4_ppm * Barometric_P) /(0.0821*Headspace_Equil_Temp_K), # in umol/L
         Source_Gas_CO2_umol = (Source_Gas_Mixing_CO2_ppm * Barometric_P) /(0.0821*Headspace_Equil_Temp_K), # in umol/L
         Final_Headspace_CH4_umol =  (Final_Headspace_Mixing_CH4_ppm * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), # in umol/L
         Final_Headspace_CO2_umol =  (Final_Headspace_Mixing_CO2_ppm * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), # in umol/L

         Final_Liq_CH4_umol =  (Final_Headspace_Mixing_CH4_ppm* Bunsen_Sol_CH4 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), # in umol/L
         Final_Liq_CO2_umol =  (Final_Headspace_Mixing_CO2_ppm* Bunsen_Sol_CO2 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), # in umol/L
         Total_Gas_CH4_umol = (Final_Liq_CH4_umol * Liquid_vol) + (Final_Headspace_CH4_umol*Headspace_vol), # in umol
         Total_Gas_CO2_umol = (Final_Liq_CO2_umol * Liquid_vol) + (Final_Headspace_CO2_umol*Headspace_vol), # in umol
         Original_Liq_CH4_umol = (Total_Gas_CH4_umol-(Source_Gas_CH4_umol*Headspace_vol))/Liquid_vol, # in umol/L
         Original_Liq_CO2_umol = (Total_Gas_CO2_umol-(Source_Gas_CO2_umol*Headspace_vol))/Liquid_vol) # in umol/L

write.csv(data_20221011 %>% filter(is.na(Original_Liq_CH4_umol)==F), "GC_Data_20221011_dissolved.csv", row.names = F)
```


```{r}
data_20221013 <- read.csv("../1-Raw Data/dissolved-gas/GC_Data_20221013_equil.csv") %>% 
  left_join(temps %>% select(Vial, Temp), by = "Vial") %>% 
  mutate(Barometric_P = 0.93, 
         Headspace_equil_P = 0.93, 
         Headspace_vol = 0.02, 
         Liquid_vol = 0.04, 
         Final_Headspace_Mixing_CH4_ppm = Measured.CH4.conc.ppm, 
         Final_Headspace_Mixing_CO2_ppm = Measured.CO2.conc.ppm, 
         Source_Gas_Mixing_CH4_ppm = 0, 
         Source_Gas_Mixing_CO2_ppm = 1, 
         Headspace_Equil_Temp_K = Temp + 273.15, 
         Bunsen_Sol_CH4 = (2.7182818^(-67.1962+(99.1624*(100/Headspace_Equil_Temp_K))+(27.9015*log(Headspace_Equil_Temp_K/100)))), 
         Bunsen_Sol_CO2 = (2.7182818^(-58.0931+(90.5069*(100/Headspace_Equil_Temp_K))+(22.294*log(Headspace_Equil_Temp_K/100))))*
           ((0.0821*273.15)+((-1636.75+(12.0408*273.15)-(3.27957*0.01*273.15*273.15)+(3.16528*0.00001*273.15*273.15*273.15))/1000)), 
         Source_Gas_CH4_umol = Source_Gas_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Source_Gas_CO2_umol = Source_Gas_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CH4_umol =  Final_Headspace_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CO2_umol =  Final_Headspace_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CH4_umol =  (Final_Headspace_Mixing_CH4_ppm* Bunsen_Sol_CH4 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CO2_umol =  (Final_Headspace_Mixing_CO2_ppm* Bunsen_Sol_CO2 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Total_Gas_CH4_umol = (Final_Liq_CH4_umol * Liquid_vol) + (Final_Headspace_CH4_umol*Headspace_vol), 
         Total_Gas_CO2_umol = (Final_Liq_CO2_umol * Liquid_vol) + (Final_Headspace_CO2_umol*Headspace_vol), 
         Original_Liq_CH4_umol = (Total_Gas_CH4_umol-(Source_Gas_CH4_umol*Headspace_vol))/Liquid_vol, 
         Original_Liq_CO2_umol = (Total_Gas_CO2_umol-(Source_Gas_CO2_umol*Headspace_vol))/Liquid_vol)

write.csv(data_20221013 %>% filter(is.na(Original_Liq_CH4_umol)==F), "GC_Data_20221013_dissolved.csv", row.names = F)
```

```{r}
data_20221012 <- read.csv("../1-Raw Data/dissolved-gas/GC_Data_20221012_equil.csv")

data_20221012 <- data_20221012 %>% 
  left_join(temps %>% mutate(Vial = paste0("0", Vial)) %>% select(Vial, Temp), by = "Vial") %>% 
  mutate(Barometric_P = 0.93, 
         Headspace_equil_P = 0.93, 
         Headspace_vol = 0.02, 
         Liquid_vol = 0.04, 
         Final_Headspace_Mixing_CH4_ppm = Undiluted.CH4.conc.ppm, 
         Final_Headspace_Mixing_CO2_ppm = Undiluted.CO2.conc.ppm, 
         Source_Gas_Mixing_CH4_ppm = 0, 
         Source_Gas_Mixing_CO2_ppm = 1, 
         Headspace_Equil_Temp_K = Temp + 273.15, 
         Bunsen_Sol_CH4 = (2.7182818^(-67.1962+(99.1624*(100/Headspace_Equil_Temp_K))+(27.9015*log(Headspace_Equil_Temp_K/100)))), 
         Bunsen_Sol_CO2 = (2.7182818^(-58.0931+(90.5069*(100/Headspace_Equil_Temp_K))+(22.294*log(Headspace_Equil_Temp_K/100))))*((0.0821*273.15)+((-1636.75+(12.0408*273.15)-(3.27957*0.01*273.15*273.15)+(3.16528*0.00001*273.15*273.15*273.15))/1000)), 
         Source_Gas_CH4_umol = Source_Gas_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Source_Gas_CO2_umol = Source_Gas_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CH4_umol =  Final_Headspace_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CO2_umol =  Final_Headspace_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CH4_umol =  (Final_Headspace_Mixing_CH4_ppm* Bunsen_Sol_CH4 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CO2_umol =  (Final_Headspace_Mixing_CO2_ppm* Bunsen_Sol_CO2 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Total_Gas_CH4_umol = (Final_Liq_CH4_umol * Liquid_vol) + (Final_Headspace_CH4_umol*Headspace_vol), 
         Total_Gas_CO2_umol = (Final_Liq_CO2_umol * Liquid_vol) + (Final_Headspace_CO2_umol*Headspace_vol), 
         Original_Liq_CH4_umol = (Total_Gas_CH4_umol-(Source_Gas_CH4_umol*Headspace_vol))/Liquid_vol, 
         Original_Liq_CO2_umol = (Total_Gas_CO2_umol-(Source_Gas_CO2_umol*Headspace_vol))/Liquid_vol)

write.csv(data_20221012 %>% filter(is.na(Original_Liq_CH4_umol)==F), "GC_Data_20221012_dissolved.csv", row.names = F)

write.csv(data_20221012 %>% filter(is.na(Original_Liq_CH4_umol)==T) %>% filter(str_detect(Vial, "^\\d{4}")==T), "GC_Data_20221012_ebullition.csv", row.names = F)
```


```{r}
data_20221014 <- read.csv("../1-Raw Data/dissolved-gas/GC_Data_20221014_equil.csv")

data_20221014 <- data_20221014 %>% 
  left_join(temps %>% mutate(Vial = paste0("0", Vial)) %>% select(Vial, Temp), by = "Vial") %>% 
  mutate(Barometric_P = 0.93, 
         Headspace_equil_P = 0.93, 
         Headspace_vol = 0.02, 
         Liquid_vol = 0.04, 
         Final_Headspace_Mixing_CH4_ppm = Undiluted.CH4.conc.ppm, 
         Final_Headspace_Mixing_CO2_ppm = Undiluted.CO2.conc.ppm, 
         Source_Gas_Mixing_CH4_ppm = 0, 
         Source_Gas_Mixing_CO2_ppm = 1, 
         Headspace_Equil_Temp_K = Temp + 273.15, 
         Bunsen_Sol_CH4 = (2.7182818^(-67.1962+(99.1624*(100/Headspace_Equil_Temp_K))+(27.9015*log(Headspace_Equil_Temp_K/100)))), 
         Bunsen_Sol_CO2 = (2.7182818^(-58.0931+(90.5069*(100/Headspace_Equil_Temp_K))+(22.294*log(Headspace_Equil_Temp_K/100))))*((0.0821*273.15)+((-1636.75+(12.0408*273.15)-(3.27957*0.01*273.15*273.15)+(3.16528*0.00001*273.15*273.15*273.15))/1000)), 
         Source_Gas_CH4_umol = Source_Gas_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Source_Gas_CO2_umol = Source_Gas_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CH4_umol =  Final_Headspace_Mixing_CH4_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Headspace_CO2_umol =  Final_Headspace_Mixing_CO2_ppm/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CH4_umol =  (Final_Headspace_Mixing_CH4_ppm* Bunsen_Sol_CH4 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Final_Liq_CO2_umol =  (Final_Headspace_Mixing_CO2_ppm* Bunsen_Sol_CO2 * Headspace_equil_P)/(0.0821*Headspace_Equil_Temp_K), 
         Total_Gas_CH4_umol = (Final_Liq_CH4_umol * Liquid_vol) + (Final_Headspace_CH4_umol*Headspace_vol), 
         Total_Gas_CO2_umol = (Final_Liq_CO2_umol * Liquid_vol) + (Final_Headspace_CO2_umol*Headspace_vol), 
         Original_Liq_CH4_umol = (Total_Gas_CH4_umol-(Source_Gas_CH4_umol*Headspace_vol))/Liquid_vol, 
         Original_Liq_CO2_umol = (Total_Gas_CO2_umol-(Source_Gas_CO2_umol*Headspace_vol))/Liquid_vol)

write.csv(data_20221014 %>% filter(is.na(Original_Liq_CH4_umol)==F), "GC_Data_20221014_dissolved.csv", row.names = F)

```

```{r}
gc1 <- read.csv("../3-Scripts/GC_Data_20221011_dissolved.csv") %>% filter(is.na(Data_Flag)==T) %>%  select(Site, Location, Rep, Collection.Date, Notes, Original_Liq_CH4_umol, Original_Liq_CO2_umol)
gc2 <- read.csv("../3-Scripts/GC_Data_20221012_dissolved.csv") %>% filter(is.na(Data_Flag)==T)%>% select(Site, Location, Rep, Collection.Date, Notes, Original_Liq_CH4_umol, Original_Liq_CO2_umol)
gc3 <- read.csv("../3-Scripts/GC_Data_20221013_dissolved.csv") %>% filter(is.na(Data_Flag)==T)%>% select(Site, Location, Rep, Collection.Date, Notes, Original_Liq_CH4_umol, Original_Liq_CO2_umol)
gc4 <- read.csv("../3-Scripts/GC_Data_20221014_dissolved.csv") %>% filter(is.na(Data_Flag)==T)%>% select(Site, Location, Rep, Collection.Date, Notes, Original_Liq_CH4_umol, Original_Liq_CO2_umol)

gc <- bind_rows(gc1, gc2, gc3, gc4)

write.csv(gc, "../2-Clean Data/dissolved-gas.csv", row.names = F)

# repeat_records <- gc %>% mutate_if(is.character, 
#                 str_replace_all, 
#                 pattern = "Picks", 
#                 replacement = "Pick") %>% 
#   mutate_if(is.character, 
#             str_replace_all,
#             pattern = "oulet", 
#             replacement = "outlet") %>% 
#   group_by(Site, Collection.Date, Location) %>% 
#   summarize(CH4_count = n()) %>% 
#   filter(CH4_count > 3) 

```


